spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: xmall
    password: yiguokeji01rabbit
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true             #开启spring amqp retry重试
          max-attempts: 5           #重试次数
          multiplier: 2             #重试时间间隔因子，下一次重试时间 = 此次间隔时间 * multiplier
          initial-interval: 2000    #初时重试时间，默认1000，即1S
          max-interval: 20000       #重试最大时间间隔
